services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techguard
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/techguard?schema=public
      NEXTAUTH_SECRET: change-me
      STRIPE_SECRET_KEY: sk_test_placeholder
      STRIPE_WEBHOOK_SECRET: whsec_placeholder
      RESEND_API_KEY: ''
      EMAIL_FROM: noreply@example.com
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    ports:
      - "3001:3000"
    command: ["pnpm", "start"]
volumes:
  pgdata:
